### ISSUE TITLE
Can't easily set the FPS in my game

### ISSUE THREAD

**Issue by philippeback** [swoolcock/diddy#55]
As the constructor of DiddyApp does some magic w/ FPS and DeltaTimer, and given that I can't override it, it is difficult to set another FPS than 60 without having to touch framework.monkey source.

**Comment by therevills** [comment]
To set the FPS just change that variable after init of the DiddyApp:

	Strict

	Import diddy

	Global game:MyGame

	Function Main:Int()
		game = New MyGame()
		game.FPS = 30
		Return 0
	End

	Class MyGame Extends DiddyApp
		Method Create:Void()
			drawFPSOn = True
			Start(New TitleScreen)
		End
	End

	Class TitleScreen Extends Screen
		
		Method New()
			name = "TitleScreen"
		End
		
		Method Load:Void()
		End
		
		Method Start:Void()
		End
		
		Method Update:Void()
		End
		
		Method Render:Void()
			Cls
			DrawText(name, SCREEN_WIDTH2, SCREEN_HEIGHT2, 0.5, 0.5)
		End
	End

(This works because on how Monkey works in the back end...)

If you need to set it dynamically, you can create little method without touching the framework code:
	Method SetFPS:Void(amount:Int)
		game.FPS = amount
		dt.targetfps = game.FPS
		dt.lastticks = Millisecs()
		SetUpdateRate(game.FPS)
	End

I'll add this in the future to the main framework module later.

**Comment by therevills** [comment]
Added to DiddyApp

**Comment by philippeback** [comment]
Ah, thanks. I was concerned about the dt aspect. This solves it.
